"""
MCP Config Generator — Create unified ~/.agent-corex/mcp.json from installed servers.

This reads server definitions from all detected AI tools (Claude, Cursor, VS Code, etc.)
and merges them into a single mcp.json file that can be used by the MCP gateway.
"""

import json
import pathlib
from typing import Dict, Any, List, Optional
import os
from datetime import datetime


class MCPConfigGenerator:
    """Generate unified MCP configuration from installed servers."""

    MCP_CONFIG_FILE = pathlib.Path.home() / ".agent-corex" / "mcp.json"
    ENV_FILE = pathlib.Path.home() / ".agent-corex" / ".env"

    @classmethod
    def generate_config(cls, include_env: bool = True) -> Dict[str, Any]:
        """
        Generate mcp.json configuration from detected AI tools.

        This scans all detected AI tools for their MCP server definitions
        and creates a unified config file.

        Returns:
        {
            "mcpServers": {
                "server_name": {
                    "command": "...",
                    "args": [...],
                    "env": {...}
                }
            }
        }
        """
        from agent_core.detectors import (
            ClaudeDesktopDetector,
            CursorDetector,
            VSCodeDetector,
            VSCodeInsidersDetector,
            VSCodiumDetector,
        )
        from agent_core.config_adapters import (
            ClaudeAdapter,
            CursorAdapter,
            VSCodeStableAdapter,
            VSCodeInsidersAdapter,
            VSCodiumAdapter,
        )

        tools = [
            ("claude", ClaudeDesktopDetector(), ClaudeAdapter()),
            ("cursor", CursorDetector(), CursorAdapter()),
            ("vscode", VSCodeDetector(), VSCodeStableAdapter()),
            ("vscode-insiders", VSCodeInsidersDetector(), VSCodeInsidersAdapter()),
            ("vscodium", VSCodiumDetector(), VSCodiumAdapter()),
        ]

        # Collect servers from all tools
        collected_servers: Dict[str, Dict[str, Any]] = {}

        for tool_slug, detector, adapter in tools:
            if not detector.is_installed():
                continue

            try:
                servers = adapter.get_servers()
                for name, server_def in servers.items():
                    # Skip agent-corex itself (it's the gateway)
                    if name == "agent-corex":
                        continue

                    # Remove "type": "stdio" if present (not needed in mcp.json)
                    cleaned_def = {k: v for k, v in server_def.items() if k != "type"}

                    if name not in collected_servers:
                        collected_servers[name] = cleaned_def
            except Exception:
                pass

        # Load and inject env variables if available
        if include_env:
            env_vars = cls._load_env_file()
            for server_name, server_def in collected_servers.items():
                if env_vars:
                    server_def.setdefault("env", {}).update(env_vars)

        return {"mcpServers": collected_servers}

    @classmethod
    def write_config(cls, config: Optional[Dict[str, Any]] = None) -> pathlib.Path:
        """
        Write mcp.json to disk.

        If config is None, generates it fresh.
        """
        if config is None:
            config = cls.generate_config()

        cls.MCP_CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)

        # Add comment
        output = {
            "_comment": "Generated by: agent-corex generate-mcp-config",
            "_timestamp": datetime.utcnow().isoformat() + "Z",
            **config,
        }

        with open(cls.MCP_CONFIG_FILE, "w") as f:
            json.dump(output, f, indent=2)

        return cls.MCP_CONFIG_FILE

    @classmethod
    def _load_env_file(cls) -> Dict[str, str]:
        """Load environment variables from ~/.agent-corex/.env"""
        env_vars = {}

        if not cls.ENV_FILE.exists():
            return env_vars

        try:
            with open(cls.ENV_FILE) as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    if "=" in line:
                        k, v = line.split("=", 1)
                        env_vars[k.strip()] = v.strip()
        except Exception:
            pass

        return env_vars

    @classmethod
    def validate_config(cls, config_path: Optional[pathlib.Path] = None) -> tuple[bool, List[str]]:
        """
        Validate mcp.json format and content.

        Returns (is_valid, list_of_errors)
        """
        if config_path is None:
            config_path = cls.MCP_CONFIG_FILE

        if not config_path.exists():
            return False, [f"Config file not found: {config_path}"]

        errors = []

        try:
            with open(config_path) as f:
                data = json.load(f)

            # Check structure
            if "mcpServers" not in data:
                errors.append("Missing 'mcpServers' key in config")
                return False, errors

            mcp_servers = data["mcpServers"]

            # Check each server
            for server_name, server_def in mcp_servers.items():
                if not isinstance(server_def, dict):
                    errors.append(f"Server '{server_name}': definition must be an object")
                    continue

                if "command" not in server_def:
                    errors.append(f"Server '{server_name}': missing 'command' field")

                if "args" in server_def and not isinstance(server_def["args"], list):
                    errors.append(f"Server '{server_name}': 'args' must be an array")

            if errors:
                return False, errors

            return True, []

        except json.JSONDecodeError as e:
            return False, [f"Invalid JSON: {e}"]
        except Exception as e:
            return False, [f"Error reading config: {e}"]
