"""Data models for input abstraction layer.

Defines the structure of human-friendly tool inputs and their mapping to internal MCP parameters.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class InputField:
    """A user-facing tool input parameter.

    Attributes:
        name: Parameter name as MCP sees it (e.g., "environment")
        display_name: Human-readable label (e.g., "Environment")
        description: Help text shown to user
        type: JSON Schema type: "string", "integer", "boolean", "array", "object"
        required: True if user must provide this
        default: Default value if not provided
        enum: List of allowed values (for select fields)
        examples: Example values for guidance
    """

    name: str
    display_name: str
    description: str
    type: str
    required: bool
    default: Any = None
    enum: list[str] | None = None
    examples: list[str] | None = None


@dataclass
class InternalParam:
    """An internal parameter resolved by the abstraction layer.

    Never shown to the LLM or user. Examples: workspacePath, projectId, userId.

    Attributes:
        name: Parameter name in MCP schema
        resolution_strategy: How to resolve this param:
            - "workspace_path": from server config or os.getcwd()
            - "user_id": from local config
            - "config_key": from server_config["env"][config_key]
            - "auth_token": from server environment
            - "static": hardcoded static_value
        config_key: Environment variable key to read (used by "config_key" strategy)
        static_value: Static value to inject (used by "static" strategy)
    """

    name: str
    resolution_strategy: str
    config_key: str | None = None
    static_value: Any = None


@dataclass
class ToolInputSchema:
    """The abstracted input schema for a tool.

    Separates user-facing inputs from internal parameters. The LLM only sees
    required_inputs and optional_inputs. Internal parameters are resolved
    automatically during execution.

    Attributes:
        tool_name: Name of the tool
        server: MCP server name (e.g., "railway")
        required_inputs: Parameters the user must provide
        optional_inputs: Parameters the user may provide
        internal_params: Parameters resolved automatically (hidden from user)
        is_auto_generated: True if generated by ParamClassifier, False if manually overridden
    """

    tool_name: str
    server: str
    required_inputs: list[InputField]
    optional_inputs: list[InputField]
    internal_params: list[InternalParam]
    is_auto_generated: bool = True
